### ISSUE TITLE
project does not compile(

### ISSUE THREAD

**Issue by alexeydott** [ashumkin/Want#1]
because missing some externals:

..\lib\Common (units uEncoder,uConsole,uFileVersion etc)
..\lib\dcpcrypt2 (DCPbase64)
..\lib\RegExpr\Source (its RegExp.pas?)
..\lib\StrNatCmp
..\lib\abstractdo
..\lib\Imports

please add them

**Comment by ashumkin** [comment]
ок
I'll take a look and will add missing externals today but a little bit later (in the evening by Moscow time)

**Comment by ashumkin** [comment]
@alexeydott, Some questions: what for do you want to use "Want"?
If to build projects for Delphi >= 2007 you might better use MSBuild.

**Comment by alexeydott** [comment]
a have 2 big projects on delphi 7. And some .*bat files to compile/build them
legacy code: sad but true)

**Comment by ashumkin** [comment]
fixed with 833f7dc

**Comment by alexeydott** [comment]
thx)
